# Generated by Django 3.1.3 on 2021-12-14 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211214_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitems',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
