# Generated by Django 3.1.3 on 2021-12-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211214_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitems',
            name='dateTime',
            field=models.DateTimeField(),
        ),
    ]
