# Generated by Django 3.1.3 on 2021-12-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211214_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitems',
            name='dateTime',
        ),
    ]
